server:
  port: 9000
# http://localhost:9000/h2-console
# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:springboot_study
    username: sa
    password: 123456
  h2:
    console:
      # 网页访问的默认路径
      path: /h2-console
      # 打开网页访问，默认为 false
      enabled: true
      # 允许远程访问
      settings:
        web-allow-others: true

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号隔开
  typeAliasesPackage: com.ittao.mybatisplus.domain
  global-config:
    refresh-mapper: true
    refresh: false
    banner: false
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
